import { Footer } from '@/layouts/Footer';
import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import './globals.css';

const dmsans = DM_Sans({
  variable: '--font-dmsans',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`relative antialiased ${dmsans.variable}`}>
        {/* <Header /> */}
        {children}
        <Footer />
        <div id='mobile-sidebar-portal' />
      </body>
    </html>
  );
}
